#!/bin/bash 
set -x
if [ "$EUID" -ne 0 ]
  then echo "You must run this as root or with sudo";
  exit 1;
fi

DbFile=""

if [ -n "$1" ]; then
    if [ $1 = "-t" ]; then
               case $2 in
            #A-record
            A )
                    echo 'Creating '"$3"'record for ip-address '"$4"' with domain address '"$5"''
                    echo "$3          IN      A       $4" >> /etc/bind/zones/db."$5"
                    DbFile="/etc/bind/zones/db.$5"
                    ;;

            #Cname-record
                CNAME )
                zone=${4#*.}
                echo "$FRONT   $ZONE"
                    DbFile="/etc/bind/zones/db.$zone"
                    echo ''"$3"'     IN      CNAME   '"$4"'.' >> "$DbFile"
                    ;;

            #MX-record
                  MX )
                    echo 'Creating '"$3"'record for ip-address '"$4"' with domain address '"$5"''
                       echo "@      IN      MX      10      $3.$5." >> /etc/bind/zones/db."$5"
                      echo "$3     IN      A       $4" >> /etc/bind/zones/db."$5"
                       DbFile="/etc/bind/zones/db.$5"
                        ;;
            esac
        else
               echo -e "$1     IN      A       $2" >> /etc/bind/zones/db."$3"
             DbFile="/etc/bind/zones/db.$3"
           fi

    #update serial
SERIAL_NUM=$(grep -Po '\d+(?=\s+; Serial)' "$DbFile")
SERIAL_LIN=$(grep -Po '\s+; Serial' "$DbFile")
SERIAL_ALL=$(grep -Po '\d+\s+; Serial' "$DbFile")

NEW_SER=$(($SERIAL_NUM + 1))
sed -i "s/$SERIAL_ALL/$NEW_SER$SERIAL_LIN/g" "$DbFile"
    
systemctl restart bind9

else
        echo -e "Invalid use"
fi

