#!/bin/bash

[[ -z "$1" ]] && { echo "Parameter 1 is empty" ; exit 1; }
vhost=$(echo $1| cut -d'.' -f 1)

sitesEnable='/etc/apache2/sites-enabled/'
sitesAvailable='/etc/apache2/sites-available/'
sitesAvailabledomain=$sitesAvailable$vhost.conf
documentRoot='/var/www/mathieu-pechovitch.sb.uclllabs.be/'
domain=$(echo $1| cut -d'.' -f 2-5)
zone=$(echo $domain| cut -d'.' -f 1) 



echo "
    <VirtualHost *:80>
      ServerAdmin root@$domain
      ServerName $1
      DocumentRoot $documentRoot$vhost
      
      ErrorLog ${APACHE_LOG_DIR}/'"$1"'-error.log
      CustomLog ${APACHE_LOG_DIR}/'"$1"'-access.log combined
    </VirtualHost>" > $sitesAvailabledomain


mkdir -p $documentRoot$vhost

echo " $vhost.$zone "  > $documentRoot$vhost/index.html
 

a2ensite $vhost

systemctl reload apache2
